version: "3.9"
services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: >
      rasa run --enable-api --cors "*" --debug

  action_server:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
    command: >
      rasa run actions --debug
