FROM python:3.10-slim

WORKDIR /app

COPY ./actions /app/actions
COPY requirements-actions.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade pip setuptools wheel
RUN pip install --no-cache-dir -r requirements.txt

CMD ["rasa", "run", "actions", "--port", "5055", "--debug"]
